### ISSUE TITLE
Plans to make this generator more like the boilerplate project?

### ISSUE THREAD

**Issue by awayken** [ben-eb/generator-postcss#1]
I decided to try my hand at writing a PostCSS plugin. I used [PostCSS Plugin Boilerplate](/postcss/postcss-plugin-boilerplate) to do so, but I had strange issues with file permissions, and I resorted to hand-generating the files myself. The second time around, I found this project, but I noticed that it creates a different style of project.

Are there plans to make the two more similar? Is one recommended by the PostCSS community over the other?

**Comment by ben-eb** [comment]
This project is configured the way it is because that's the setup I personally like and use for my plugins. Both are just starting points, you are of course free to use whatever testing strategy or external modules that you wish, as long as your plugin follows the [guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md).
